### Generated by rprotoc. DO NOT EDIT!
### <proto file: ../yamx-protobuf/yamx.proto>
# package com.srikanthps.yamx.proto;
# 
# message SysInfo {
#   required string appName = 1;
#   required string hostname = 2;
#   required string ipAddr = 3;
#   optional string systemType = 4;
#   optional string osinfo = 5;
# }
# 

require 'protobuf/message/message'
require 'protobuf/message/enum'
require 'protobuf/message/service'
require 'protobuf/message/extend'

module Com
  module Srikanthps
    module Yamx
      module Proto
        class SysInfo < ::Protobuf::Message
          defined_in __FILE__
          required :string, :appName, 1
          required :string, :hostname, 2
          required :string, :ipAddr, 3
          optional :string, :systemType, 4
          optional :string, :osinfo, 5
        end
      end
    end
  end
end